### ISSUE TITLE
Como se distribui os inscritos (aprovados e reprovados) observando se o curso foi 1ª ou 2ª opção para CC na UFCG

### ISSUE THREAD

**Issue by ricardoadley** [Guardians-DSC/dados#11]
Eu, como integrante da célula, desejo saber como se distribui os incritos no curso, ao serem aprovados ou reprovados o curso era a 1ª ou a 2ª opção deles?
- [x] Filtrar os dados para o curso de ciência da computação na UFCG
- [x] Calcular quantidade de inscritos como 1ª opção e 2ª opção
- [x] Gerar visualizações para os resultados
- [x] Descrever os achados na análise

## Criterio de aceitação
Link para acesso ao jupyter colab com os resultados e código elaborado [link do notebook](https://colab.research.google.com/drive/1MbKeqiUS_BezQmVenBOG0Z4pmoCG-xoI?usp=sharing)

**Comment by ricardoadley** [comment]
Oi Daniele, desculpe pela demora na revisão, os resultados estão ótimos você fez um trabalho muito bom com um código organizado, bem documentado e visualizações muito boas. Gostaria que você abrisse pr enviando o código e resultados para o repositório (o colab que você fez) se tiver alguma duvida / problema para fazer isso fala comigo no privado.

**Comment by danieleolivs** [comment]
obrigada! 😊
acabei de tentar fazer isso, espero que esteja tudo ok
