### ISSUE TITLE
Quantidade de aprovações e reprovações na cadeira de TC

### ISSUE THREAD

**Issue by ricardoadley** [Guardians-DSC/dados#17]
Eu, como integrante da célula, desejo saber o historico de aprovações e reprovações dos alunos na cadeira de Teoria da Computação ao longo do curso

- [x] Filtrar os dados para a cadeira de TC
- [x] Calcular a quantidade de aprovados e reprovados
- [x] Gerar visualizações para os resultados
- [x] Descrever os achados na análise

## Criterio de aceitação
Link para acesso ao jupyter colab com os resultados e código elaborado

### Fonte de dados para historico do curso
https://github.com/elasComputacao/raio-x-dados/blob/main/data/dados-brutos/historico_alunos_raiox.csv?raw=true

Link do colab com a analise dos dados da cadeira de TC:
[Aprovação Teoria da computação](https://colab.research.google.com/drive/1zQuQfgjj63wanniz27Eb0Yt6T7qShqRX?usp=sharing#scrollTo=seyyB00OsQ2i)
Analise:
As informaçoes indicam que, em media, 8 a cada 10 estudantes que realmente pagam a cadeira são aprovados, mostrando que tem um alto indice de aprovação em relação a outras cadeiras do curso

**Comment by Rafa-pb** [comment]
Link do colab com a analise dos dados da cadeira de TC
[https://colab.research.google.com/drive/1zQuQfgjj63wanniz27Eb0Yt6T7qShqRX?usp=sharing](url)

**Comment by ricardoadley** [comment]
Oi Rafel, como vc já consluiu essa primeira parte (otimo trabalho inclusive !) vamos expandir um pouco? Você poderia dar uma olhada nos periodos que tiveram mais e menos aprovações? Junto com os que apresentaram mais trancamentos e mais reprovações por falta. Também tenta comentar um pouco sobre os resultados mostrados no notebook já montando tipo um relatorio, blz?

**Comment by ricardoadley** [comment]
Oi Rafael, ta muito legal os resultados, você poderia agora comentar um pouco sobre o que foi feito e encontrado com o notebook (lá mesmo usando a opção de texto) e abrir pr enviando o código e resultados para o repositório? Se tiver duvidas / problemas para fazer isso fala comigo no privado.
