### ISSUE TITLE
Aprovação e reprovação dos estudantes de CC nas cadeiras optativas gerais (Fora do DSC)

### ISSUE THREAD

**Issue by ricardoadley** [Guardians-DSC/dados#18]
Eu, como integrante da célula, desejo saber como se distribuem as aprovações e reprovações dos alunos de CC nas optativas ofertadas por outros departamentos

- [x] Filtrar os dados para as cadeiras opitativas gerais
- [x] Calcular a quantidade de aprovados e reprovados
- [x] Gerar visualizações para os resultados
- [x] Descrever os achados na análise

## Criterio de aceitação
[Link para acesso ao jupyter colab com os resultados e código elaborado](https://colab.research.google.com/drive/17SrNtA-dl-QpglnanT87odGV1H7BmFyD?usp=sharing)

### Fonte de dados para historico do curso
https://github.com/elasComputacao/raio-x-dados/blob/main/data/dados-brutos/historico_alunos_raiox.csv?raw=true

**Comment by ricardoadley** [comment]
Ótimo trabalho Lucas, teria como você abrir pr enviando esses seus resultados para o repositório? Se tiver alguma duvida / problema para fazer isso fala comigo no privado.

**Comment by lucasqueiros** [comment]
pronto! foi a primeira vez, entao acho q fiz tudo certinho kkkkkk se eu tiver feito o pr errado tu avisa pfvr kkkkk
