### ISSUE TITLE
Onboarding e nivelamento

### ISSUE THREAD

**Issue by joaquimfarias** [Guardians-DSC/dados#23]
Eu, como novo integrante, irei realizar o onbording para iniciantes em python e pandas.

Sub-Tasks:
- [x] Realizar onboarding do notion https://www.notion.so/Baby-steps-3e6c24a8e3904cceb2cdf29eada91977
- [x] Participar do curso de introdução

Criterio de aceitação
- Participação das atividades citadas
- jupytercolab com os passos do onboarding do notion

**Comment by joaquimfarias** [comment]
https://colab.research.google.com/drive/1HmkBinhKm9i9YLXBQ9Kzin-UtMqTrvGI?usp=sharing

**Comment by ricardoadley** [comment]
Tudo certo, agora você só precisa escolher em qual frente vai atuar e irei atribuir suas tasks.
