### ISSUE TITLE
Observar onde estão as maiores e menores medias das áreas do enem e se elas mudaram com o tempo para CC na UFCG

### ISSUE THREAD

**Issue by ricardoadley** [Guardians-DSC/dados#35]
Eu, como integrante da célula, desejo ver como as medias de ingresso no curso se comportaram durante os anos.

- [x] Filtrar os dados para CC na UFCG
- [x] Identificar a maior média  de cada área por sisu (.1 e .2)
- [x] Identificar a menor média (nota de corte) de cada área por sisu (.1 e .2)
- [x] Identificar qual a área com a maior media e qual com a menor (nota de corte)
- [x] Observar o comportamento desse valor durante os anos (uma visualização como grafico talvez)
- [x] Plotar graficos sobre as medias em cada area (displot e boxplot por exemplo)

Link para acesso ao  colab com o código e resultados obtidos [Link](https://colab.research.google.com/drive/1YJ_UlZA2_aX4dbzXqF4-fZ6iXjfLGvFp?usp=sharing)

**Comment by kemillilima** [comment]
Link para acesso ao  colab com o código e resultados obtidos [Link](https://colab.research.google.com/drive/1YJ_UlZA2_aX4dbzXqF4-fZ6iXjfLGvFp?usp=sharing)

**Comment by ricardoadley** [comment]
tudo certo galera, podem abrir pr
