### ISSUE TITLE
Analise dos dados dos gastos com os Municipios informados

### ISSUE THREAD

**Issue by leofarias-cpu** [Guardians-DSC/dados#36]
Collab com a análise e conclusão [aqui](https://colab.research.google.com/drive/1eG5i-ZUAtFuhHlvtaGwP8yEgdyBDdSXY#scrollTo=xiTStzLq8Qxm)

**Comment by leofarias-cpu** [comment]
Infelizmente muito poucos gastos tem o município informado, então quase nada pode ser extraído dessa seção dos dados, mas foi divertido e bastante educativo.

**Comment by ricardoadley** [comment]
Ótimo trabalho leo, bastante interessante o observado de que esse registro é negligenciado e também o fato levantado da alocação e devolução dos valores para o hospital. Poderia pfvr abrir uma pr enviando o seu colab para o repositório?
